# Generated by Django 4.1.13 on 2024-02-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dynamic_collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
