# Generated by Django 4.1.13 on 2024-02-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_document_file_type_document_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
